### ISSUE TITLE
Elasticache L2 Constructs

### ISSUE THREAD

**Issue by jaylucas** [aws/aws-cdk-rfcs#109]
|PR|Champion|
|--|--------|
|# |        |

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Duplicate https://github.com/aws/aws-cdk/issues/6908

**Comment by eladb** [comment]
Tracked as a construct library
