### ISSUE TITLE
CDK to directly reference/import/update an existing stack

### ISSUE THREAD

**Issue by cathalaherne2** [aws/aws-cdk-rfcs#127]
|PR|Champion|
|--|--------|
|# |        |

## Description

allow CDK to directly reference/import/update an existing stack  that is created via the cloudformation console/ CLI.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
This is not sufficient information for us to be able to start the RFC process. Please follow the instructions in README on how to submit an RFC for review.

Closing for now.
