### ISSUE TITLE
Toolchain 2.0

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#14]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Modular toolchain
- [ ] Library support (allow toolchain modules to be used as a library in all jsii languages)
- [ ] Interactive deploy tree
- [ ] Tree-based diff (with support for CI/CD approvals)
- [ ] Built-in Lambda local invocation
- [ ] Nested stacks in diff and deployments

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
Interested. Details?

**Comment by awsmjs** [comment]
Closing as this ticket has gone stale and is not a current priority.
