### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#15]
|PR|Champion|
|--|--------|
|# |        |

## Description

Add CLI/IDE support for adding project elements like:

 - [ ] new construct
 - [ ] add lambda function (handler + construct)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by alzateja** [comment]
Not sure if valuable but I recently released an npm package that may be relevant. Just a heads up. - https://www.npmjs.com/package/aws-cdk-gen

**Comment by marcioemiranda** [comment]
The company I work for has a goal of developing an accelerator program consisting of a collection of custom patterns and reference applications.
We plan to build a cli app to facilitate the creation of certain projects.  For example, a developer could create a new Microservice app, which is actually a template of a CDK app containing custom constructs (Microservice) + ci/cd + best practices. From that point, he would use the cli to generate an API by providing a schema (Open API specification, for example). The scaffolding process would generate infrastructure (Constructs for API Gateway, Lambda) and runtime code. The runtime code could add external dependencies to handle a Controller like functionality. In the case of a Python runtime, it could use AWS Lambda Power Tools to bring lots of functionality like observability, API routing, validation, among others.
The same functionality could be used for domain event handling, i.e, inform a schema and generate infra + runtime (event handler, validation, etc)

**Comment by marcioemiranda** [comment]
Hey @eladb,  I've just watched your talk on CDK Day 2021 showing how to generate Infra + runtime to abstract DynamoDB usage given a domain model. This is another use case for the project mentioned above. So, it looks like Projen is the way to go!

**Comment by mrgrain** [comment]
[projen can ](https://github.com/projen/projen) can do this.
