### ISSUE TITLE
Cross-Region/Account References

### ISSUE THREAD

**Issue by SachinShekhar** [aws/aws-cdk-rfcs#161]
An idea to fix cross-region/account resource sharing issue which goes beyond resource sharing capabilities of CloudFormation.

### Use Case

CDK is a wonderful product which should get Best Cloud Innovation Award. It allows us to create super complex cloud infrastructure quickly without needing a team of hundreds or thousands.

Cross-region/account resource sharing is only natural for even small projects. It should have worked smoothly like same env resource sharing. Unfortunately, only those references which doesn't involve CloudFormation work (that's also if we provide `PhysicalName` or use `core.PhysicalName.GENERATE_IF_NEEDED`). To reference CloudFormation  generated refs, we need to use complex strategies using `NestedStack`, `CustomResource`, `ProviderFramework`.

This feature will make everything smooth and simple. Users will be able to share resources across stacks without thinking about stack's env. Splitting existing CDK apps across multiple accounts will also become easy.

### Proposed Solution

1. If there are circular dependencies across stacks, throw error.

2. Synthesize and deploy only those stacks which are dependencies.

3. Retrieve resolved refs from previous step and use them to synthesize and deploy dependent stacks.

4. Repeat the last step if there are more dependent stacks.

### Other

`CDK Synth` won't be able to work without deployment, so it should throw error if there are cross-region/account references. It shouldn't be called BREAKING CHANGE because existing CDK apps won't be affected. This is a small price to pay if someone wants to use new cross-region/account reference feature. Maybe, to make existing behavior same, a new flag in `App` class can be introduced which will need to be turned ON to use this new feature.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by pgollucci** [comment]
"I would encourage you to consider designs that "stay within the bounds" of the current model. For example, use CFN custom resources to query values across environments during deployment."

If that's the best practice that needs to go in the docs.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
