### ISSUE TITLE
CLI support for multiple-environments

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#17]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Profiles?
- [ ] Assuming roles?

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
Can you shed some light on what and Environment is and how the user might interact?

**Comment by virajkanwade** [comment]
@pgollucci probably referring to https://github.com/aws/aws-cdk/pull/23912
