### ISSUE TITLE
Generating CloudFormation resources from CloudFormation Registry schemas

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk-rfcs#197]
|PR|Champion|
|--|--------|
|# |        |

## Description

This proposal is to stop generating the CloudFormation Resources (also known as *`Cfn*` classes* / *L1 Constructs*) from the legacy [CloudFormation Resource Specification] document, and instead to leverage the improved schema that is provided as part of the [CloudFormation Registry].

[CloudFormation Resource Specification]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
[CloudFormation Registry]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Duplicate #77
