### ISSUE TITLE
Support for CloudFormation Resource Imports

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#2]
|PR|Champion|
|--|--------|
|# |        |

## Description

CloudFormation released[ resource import](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-supported-resources.html
)
How should we support it in the CDK?

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by rantoniuk** [comment]
Is anything happening to this RFC? some issues were referenced as being handled/discussed under this one, but I don't see much activity happening but I'd like to know the direction we should go with IaaC for the mentioned issues (e.g. #15296)

**Comment by eladb** [comment]
See https://github.com/cdklabs/cdk-import

**Comment by rantoniuk** [comment]
Thanks for the link, is there any roadmap for this being added to aws-cdk? 2.x? 1.x?

**Comment by eladb** [comment]
Not at the moment, but you should be able to use this already. We are looking to collect some real-world feedback and mature this tool before we integrate into the CDK CLI.

**Comment by eladb** [comment]
Duplicate #52
