### ISSUE TITLE
Cost calculator

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#22]
|PR|Champion|
|--|--------|
|# |        |

## Description

https://github.com/aws/cdk-ops/issues/411

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by gabrielenosso** [comment]
Looks like duplicate of Number 70 (or viceversa :)

**Comment by evgenyka** [comment]
Closed as duplicate of https://github.com/aws/aws-cdk-rfcs/issues/70
