### ISSUE TITLE
Bootstrap stacks as CDK apps

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk-rfcs#242]
|PR|Champion|
|--|--------|
|# | @nija-at    |

## Description

The bootstrap stack is a CloudFormation template. Wouldn't it be cool if it was a CDK stack, built from CDK constructs?

Wouldn't it be even cooler if we could directly install it from NPM with a nice UI? (a la applets)

See discussion at https://github.com/aws/aws-cdk/pull/9886

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
A very important tenant that must be preserve is that bootstrap templates should be usable through account stamping tools like StackSets and Control Tower/Landing Zone. 

This implies that we should enforce/ensure that the same bootstrap template can be used for multiple environments.

This implies that all degrees of freedom should be expressable through cfn parameters and the CDK CLI should not synthesize the bootstrap stack per environment.

So using the CDK should be kept to synthesizing a "pure" reusable cfn template (which is against the normal style of using the CDK).

**Comment by skinny85** [comment]
We could go really meta, and use the [`@aws-cdk/cloudformation-include` module](https://docs.aws.amazon.com/cdk/api/latest/docs/cloudformation-include-readme.html) to implement this 😃
