### ISSUE TITLE
Generating L1s from CloudFormation Registry Schema Format

### ISSUE THREAD

**Issue by rix0rrr** [aws/aws-cdk-rfcs#264]
|PR|Champion|
|--|--------|
|# |        |

## Description

Instead of consuming the CloudFormation Resource Specification format to generate the set of L1s, we should we consuming the CloudFormation Registry Schema Format instead.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
Duplicate with #77
