### ISSUE TITLE
CI/CD to Cloudfront Deploy

### ISSUE THREAD

**Issue by iqbal125** [aws/aws-cdk-rfcs#272]
|PR|Champion|
|--|--------|
|# |        |

## Description

A very common use case for AWS users is to build a CI/CD pipeline that deploys to Cloudfront. Having a "pattern" that does this automatically for a SPA app like React I think would be helpful for a lot of people. 

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
[CDK pipelines] is able to deploy CloudFront resources as well as any other resource. Combined with the [s3-deployment] module, this should cover your use case.

[CDK pipelines]: https://aws.amazon.com/blogs/developer/cdk-pipelines-continuous-delivery-for-aws-cdk-applications/
[s3-deployment]: https://docs.aws.amazon.com/cdk/api/latest/docs/aws-s3-deployment-readme.html

Closing.
