### ISSUE TITLE
Deprecated API Warnings

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk-rfcs#287]
## Description

If an element in the CDK Construct Library (class, interface, property, function, etc.) is deprecated, using it inside a CDK application should produce a warning in the CDK CLI for all commands that perform synthesis (`cdk synth`, `cdk diff`, `cdk deploy`, etc.).

This will aid in the migration from CDK `V1` to `V2`.

## Roles

| Role                | User
|---------------------|------------------------------
| Author(s)           | @skinny85 
| API Bar Raiser      | @eladb 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by eladb** [comment]
@skinny85 has this been implemented already?

**Comment by skinny85** [comment]
@eladb no, it has not - the design has been approved in the RFC, but the implementation work has not started.
