### ISSUE TITLE
Policy Definition and Enforcement

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#294]
|PR|Champion|
|--|--------|
|# |  @eladb       |

## Description

We want to allow users to be able to define and share policy rules which will be executed during synthesis (CLI/aspects), deployment (CloudFormation hooks?) and maybe even at runtime (AWS Config?).

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by lielran** [comment]
+1 for aws config

**Comment by evgenyka** [comment]
Implemented via https://github.com/cdklabs/cdk-validator-cfnguard.
See https://docs.aws.amazon.com/cdk/v2/guide/policy-validation-synthesis.html for more details.
Community plugin for Checkov: https://github.com/bridgecrewio/cdk-validator-checkov
