### ISSUE TITLE
support code signing of assets

### ISSUE THREAD

**Issue by dontirun** [aws/aws-cdk-rfcs#305]
Related to https://github.com/aws/aws-cdk/pull/12656 , https://github.com/aws/aws-cdk/issues/12216

Created a Lambda `SignedCode.fromAsset`  option that takes local code uploads it to S3 and signs it using a specified AWS signer profile

### Use Case

With PR https://github.com/aws/aws-cdk/pull/12656 Lambda now supports a code signing configuration. However if the signing config is set to `Enforce` and local code (inline or from asset path) is provided the deployment will fail as the code has not been signed

```typescript
      const signingProfile = new signer.SigningProfile(stack, 'SigningProfile', {
        platform: signer.Platform.AWS_LAMBDA_SHA384_ECDSA,
      });

      const codeSigningConfig = new lambda.CodeSigningConfig(stack, 'CodeSigningConfig', {
        signingProfiles: [signingProfile],
        untrustedArtifactOnDeployment: lambda.UntrustedArtifactOnDeployment.ENFORCE,
      });

      new lambda.Function(stack, 'MyLambda', {
        code: new lambda.Code.fromAsset(...),
        handler: 'index.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        codeSigningConfig,
      });
  ```

this feature would enable usage of local code and signing of the the code given permissions to the signing profile

### Proposed Solution

Having an option like
```typescript
     new lambda.Function(stack, 'MyLambda', {
        code: new lambda.SignedCode.fromAsset(...),
        handler: 'index.handler',
        runtime: lambda.Runtime.NODEJS_10_X,
        codeSigningConfig,
      });
```
would solve this issue

### Other
1. This is [how the SAM CLI does it](https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/package/code_signer.py)
2. The bootstrap bucket would need to have [versioning enabled](https://github.com/aws/aws-cli/blob/5aa599949f60b6af554fd5714d7161aa272716f7/awscli/examples/signer/start-signing-job.rst)

* [x] :wave: I may be able to implement this feature request
* [x] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by derekmurawsky** [comment]
Just curious if there have been any thoughts on this since the original posts. We're actively using CDK now and would like to have our code signed for compliance purposes. Are there any clever approaches we can leverage here, or do we need to build our own process from scratch?

**Comment by awsmjs** [comment]
Closing as we unfortunately do not have the bandwidth to work on this in the near future. We suggest to pursue experimentation in a separate package or a fork if needed. If a successful implementation emerges, reopen the proposal with details on the functionality and how it can be implemented in the core library.
