### ISSUE TITLE
CDK third-party dependencies management

### ISSUE THREAD

**Issue by skinny85** [aws/aws-cdk-rfcs#317]
## Description

The CDK depends on many third-party open-source libraries. Because of that, it needs to manage what happens when a security issue is found in one of them, and how do we defend against supply chain attacks.

## Roles

* **Driver** (drives the proposal to completion): @skinny85
* **Approver(s)**: (assigned by CDK team)

**Comment by niebloomj** [comment]
What is the proposition here? Sounds interesting.

**Comment by sholtomaud** [comment]
I reckon this issue should raise the question about AWS funding these 3rd party tools in a business partnership model. A tool like @feross [@SocketDev](https://socket.dev/) could really shine here, but again, a funding and license model is key.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` like the associated PR. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
