### ISSUE TITLE
Third-party construct ecosystem

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#34]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Construct gallery
- [ ] "jsii" init template
- [ ] Blog post on how to write and publish a multi-language construct library

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
Any news ?
