### ISSUE TITLE
Publish construct library guidelines

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#35]
|PR|Champion|
|--|--------|
|# |        |

## Description

- [ ] Publish construct library guidelines
- [ ] Document all awslint rules (in the guidelines)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by wulfmann** [comment]
I’m excited to see the core teams thoughts around this RFC. I’ve been managing an internal 3rd party library at work and it has been a great experience. I’ve tried to model it on what CDK itself currently looks like, but would love to see some kind of formal spec.

**Comment by pgollucci** [comment]
Any news here?

**Comment by eladb** [comment]
This was actually published under https://github.com/aws/aws-cdk/blob/master/docs/DESIGN_GUIDELINES.md

Closing
