### ISSUE TITLE
Constructs Programming Model

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#36]
|PR|Champion|
|--|--------|
|# |        |

## Description

The AWS CDK demonstrates that leveraging general purpose programming languages
to define complex configuration modules brings value to users. At the heart of
the AWS CDK lies the "constructs programming model" which consists of a simple
pattern that enables composition and synthesis.

Recently, there were a few initiatives to build CDKs for other domains with
similar characteristics. Examples are Kubernetes, Terraform and GitHub Actions.

We wish to enable the creation of these "sister" CDK projects by extracting the
constructs programming model into an independent library, which can be leveraged
for any domain without taking a dependency on the AWS CDK.

In order to enable composition of constructs across domains (e.g. Kubernetes app
defined within an AWS CDK app), we will need to extract the `Construct` base
class from the @aws-cdk/core module and into a separate module and AWS CDK users
will need to take a dependency on this new module.

> Note that this means that all CDK apps and libraries will also need to take a peer dependency on this new module.

Spaces:
- [ ] Terraform
- [ ] Kubernetes
- [ ] F5

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgollucci** [comment]
I am interested in this. Dare I say it other Clouds?  But no really, Kubernetes

**Comment by eladb** [comment]
We have released this as an independent library called [constructs] and also have an alpha version of https://cdk8s.io

[constructs]: https://github.com/aws/constructs

**Comment by pgollucci** [comment]
This seems done esp with 10.x.  Can be closed?

**Comment by eladb** [comment]
Yes, done.

**Comment by jjkavalam** [comment]
@eladb Where could i find an introduction to the Constructs Programming Model ? I can see that the idea is really effective; but i would like to get some guidance on using it. I am interested in applying it on a domain different from aws/k8s.

The readme at https://github.com/aws/constructs is unfortunately not quite helpful.
