### ISSUE TITLE
The jsii compiler to follow TypeScript versioning

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk-rfcs#374]
## Description

This RFC proposes to change the versioning scheme of the `jsii` compiler to stop
conforming to semantic versioning, and instead use the `major.minor`
version of the TypeScript compiler it is built on.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @RomainMuller
| Author(s)           | @RomainMuller
| API Bar Raiser      | TBD
| Stakeholders        | @iliapolo, @MrArnoldPalmer

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by awsmjs** [comment]
Closing ticket as this was merged.
