### ISSUE TITLE
CDK Testing Toolkit

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#4]
|PR|Champion|
|--|--------|
|# |   @nija-at      |

## Description

- [ ] Assert Library
- [ ] Integration testing tool
- [ ] CI/CD integration test support

Improvements to integration testing tool:

- [ ] Add a source hash to avoid manual updates
- [ ] Run periodically in a pipeline
- [ ] Support assertions (through custom resources)
- [ ] Support snapshotting the full cloud assembly

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by campionfellin** [comment]
Hey @eladb is this being worked on by anyone? I think it'd be helpful to other developers to officially vend CDK tools like those found here: https://github.com/aws/aws-cdk/tree/master/tools 

I'd like to give a shot at writing an RFC for this.

**Comment by eladb** [comment]
@campionfellin, can you please sync up with @nija-at about this? We just talked about it the other day and I believe he considered started looking into it.

**Comment by pgollucci** [comment]
where did it land ?

**Comment by nija-at** [comment]
Assertions library was RFC'ed here - https://github.com/aws/aws-cdk-rfcs/blob/master/text/0328-polyglot-assert.md and has been released.

We're tracking RFC for integration tests here - https://github.com/aws/aws-cdk-rfcs/issues/31. The work for this is starting soon.

If there are other testing ideas or support, let's open separate tracking issues for them. Closing this issue 'catch all' issue.
