### ISSUE TITLE
Documentation for DEPRECATED environment variable does not match CDK behavior

### ISSUE THREAD

**Issue by raginjason** [aws/aws-cdk-rfcs#414]
## Description

It appears that the documentation regarding the `DEPRECATED` environment variable does not match the manner with which CDK behaves:
* The environment variable appears to be `JSII_DEPRECATED` instead of `DEPRECATED`
* For CDK to throw an exception, this environment variable should have a value of `fail` instead of `error`.

This was tested against CDK v1.148.0

**Comment by Chriscbr** [comment]
Fixed by #416
