### ISSUE TITLE
AppConfig L2 Construct

### ISSUE THREAD

**Issue by yamatatsu** [aws/aws-cdk-rfcs#426]
## Description

I would like to implement AppConfig L2 Construct. It has already got enough votes (see, https://github.com/aws/aws-cdk/issues/6831). Also, I believe that CDK, which is more application-oriented than CFn, will be able to manage AppConfig well, which will create a variety of value.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @yamatatsu
| Author(s)           | @alias, @alias, @alias
| API Bar Raiser      | @alias
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by neo01124** [comment]
Is this L2 construct already merged? Wondering since this issue is completed but the feature request is open https://github.com/aws/aws-cdk/issues/6831

**Comment by evgenyka** [comment]
No, it was not implemented, the RFC was abandoned.
