### ISSUE TITLE
Amazon GameLift L2 Constructs

### ISSUE THREAD

**Issue by stevehouel** [aws/aws-cdk-rfcs#436]
## Description

Amazon GameLift is a game server hosting solution. This construct library allows CDK users to create the infrastructure to easily configure their matchmaking rules and game server fleets.

The aim of this library is to provide an even easier way of defining the Matchmaking rules components and fleet management system needed to deploy and host their game server by providing constructs with more guard rails and contextual information to get users going straight away.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @stevehouel
| Author(s)           | @stevehouel
| API Bar Raiser      | @otaviomacedo 
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by mrgrain** [comment]
Alpha released: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-gamelift-alpha-readme.html
