### ISSUE TITLE
AWS Compute Optimizer Constructs

### ISSUE THREAD

**Issue by ractille** [aws/aws-cdk-rfcs#448]
## Description

This is a proposal for two constructs. The first is a L2 construct that interfaces with AWS Compute Optimizer apis in order to opt-in/out or set recommendation preferences. As a result, people can set up Compute Optimizer when they create new resources without needing to separately go to the AWS CLI or website. The second is an L3 construct that calls ACO export APIs, and allows customers to set a recurring export job as that is not currently supported by ACO.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @ractille
| Author(s)           | @alias, @alias, @alias
| API Bar Raiser      | @alias
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
