### ISSUE TITLE
Glue View L2 Construct

### ISSUE THREAD

**Issue by JeromeGuyon** [aws/aws-cdk-rfcs#463]
## Description

Supports Views as a L2 construct in aws-glue cdk library

It allows to create Presto Views directly from the SQL Statement.

With :

- that columns that must be a subset of declared columns in SQL Statement, but no sush checks. No checks on column typing consistency with SQL Statement.
- No checks on the SQL Statement.

Example of usage : 

```ts
declare const myDatabase: glue.Database;

new glue.View(this, 'MyView', {
  database: myDatabase,
    tableName: 'my_view',
    columns: [{
      name: 'col',
      type: glue.Schema.STRING,
    }],
    sql: 'select "1" as col',
  });
```

The Glue View is a special `Glue Table`, with readonly access on data and should share the maximum of attributes/members for Table L2 Construct.

### Draft PR:

Draft PR : https://github.com/aws/aws-cdk/pull/22459

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @JeromeGuyon
| Author(s)           | @JeromeGuyon
| API Bar Raiser      | 
| Stakeholders        | 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
