### ISSUE TITLE
EventBridge Scheduler L2 Construct

### ISSUE THREAD

**Issue by filletofish** [aws/aws-cdk-rfcs#474]
## Description

EventBridge Scheduler was released on 2022/11. It is basically a powerful version of the existing EventBridge scheduled rules, with more scalability, timezone support, time window schedules, etc. [Introducing Amazon EventBridge Scheduler](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/)

This RFC will propose a L2 construct for  Amazon EventBridge Scheduler, which will be a more user-friendly version of existing L1 (CloudFormation) Construct (see [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html)).

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         |  @ffilipp, @Jacco
| Author(s)           | @ffilipp, @Jacco
| API Bar Raiser      | @kaizencc 
| Stakeholders        | 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [x] Community reach out (via Slack and/or Twitter)
- [x] API signed-off (label `api-approved` applied to pull request)
- [x] Final comments period (label: `status/final-comments-period`)
- [x] Approved and merged (label: `status/approved`)
- [x] Execution plan submitted (label: `status/planning`)
- [x] Plan approved and merged (label: `status/implementing`)
- [x] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by roshni06** [comment]
Hi what is the status of this feature in CDK and when will this be released?

**Comment by jakegrabowski** [comment]
Also waiting for it :)

**Comment by mrgrain** [comment]
`scheduler-alpha` has been released for a while 🎉 

https://docs.aws.amazon.com/cdk/api/v2/docs/aws-scheduler-alpha-readme.html

**Comment by deeTEEcee** [comment]
@mrgrain any idea when is it gonna get out of alpha state?

**Comment by mrgrain** [comment]
> @mrgrain any idea when it's gonna get out of alpha?

No sorry. Plus I'm not working on the AWS CDK anymore.

The best way to help is by using the alpha module and opening issues for any problems you encounter.
