### ISSUE TITLE
Amazon OpenSearch Serverless L2 Construct

### ISSUE THREAD

**Issue by cprakasu** [aws/aws-cdk-rfcs#492]
## Description
[
Amazon OpenSearch Serverless](https://aws.amazon.com/opensearch-service/features/serverless/) has been general available since January 2023. I would like the L2 constructs implemented to ease the usage of the service.

The main goal of L2 is to simplify creation of Collections. 

Creating OpenSearch Serverless collection with L1 constructs requires creating multiple resources in a particular order: Collection, Encryption Policy, Network Policy and Security Config. 
The L2 construct would allow a single api to manage all related resources for a collection.

There are other improvements around the different policy resources. CDK construct should allow to validate policies at compile time.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @cprakasu
| Author(s)           | @cprakasu
| API Bar Raiser      | 
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.

**Comment by rhermes62** [comment]
Is AWS CDK then moving away from vending L2 constructs? Or is this just the wrong folder for requesting this L2 construct?

**Comment by mrgrain** [comment]
> Is AWS CDK then moving away from vending L2 constructs? Or is this just the wrong folder for requesting this L2 construct?

We are refocusing the RFC repo on core framework changes, which explicit doesn't include new L2s. You may still open feature requests in the main repo [aws/aws-cdk](https://github.com/aws/aws-cdk). However the AWS CDK team prioritizes new L2s based on a number of criteria and you can see our current focus area in the quarterly updated [ROADMAP](https://github.com/aws/aws-cdk/blob/main/ROADMAP.md). 

For any L2s that are not currently on the roadmap we encourage the community to publish and vend them as separate packages.
