### ISSUE TITLE
Standardize GitHub issues escalation process

### ISSUE THREAD

**Issue by RomainMuller** [aws/aws-cdk-rfcs#50]
|PR|Champion|
|--|--------|
|# |        |

## Description
Standardize a process around escalating issues, when to pin and unpin issues, etc... So that the process is consistent and mechanical.

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by eladb** [comment]
@iliapolo I believe this is done, right?
