### ISSUE TITLE
Add Step Functions SageMaker CreateProcessingJob task construct

### ISSUE THREAD

**Issue by athewsey** [aws/aws-cdk-rfcs#509]
## Description

As described in https://github.com/aws/aws-cdk/issues/9537, the `aws-cdk-lib/aws-stepfunctions-tasks` package currently [implements task states](https://github.com/aws/aws-cdk/tree/main/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker) for some of the [optimized SageMaker service integrations](https://docs.aws.amazon.com/step-functions/latest/dg/connect-sagemaker.html) such as [`SageMakerCreateModel`](https://github.com/aws/aws-cdk/blob/1d7a9a80b08d41ce8759bed9286adaa8259c2bc8/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-model.ts#LL72C1-L72C1) and [`SageMakerCreateTrainingJob`](https://github.com/aws/aws-cdk/blob/1d7a9a80b08d41ce8759bed9286adaa8259c2bc8/packages/aws-cdk-lib/aws-stepfunctions-tasks/lib/sagemaker/create-training-job.ts#L101), but not for the [sagemaker:createProcessingJob task](https://docs.aws.amazon.com/step-functions/latest/dg/connect-sagemaker.html#sagemaker-example-processing).

In particular, the `arn:aws:states:::sagemaker:createProcessingJob.sync` task is useful for users because it *waits for the processing job to complete* - whereas just using an AWS service/SDK `sagemaker:createProcessingJob` step would require additional states to monitor job status.

There were some previous attempts to get a solution merged in 2020 by @heatsink, but seems like a design was not agreed and to my understanding this RFC process would be the next step to make that happen(?)

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @athewsey
| Author(s)           |
| API Bar Raiser      |
| Stakeholders        |

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
