### ISSUE TITLE
AppSync Merged API L2 construct

### ISSUE THREAD

**Issue by jumic** [aws/aws-cdk-rfcs#526]
## Description

This RFC proposes a new L2 construct to support AppSync Merged APIs. Merged APIs can be used to combine multiple AppSync source APIs into a single (merged) AppSync API.

Compared to the existing AppSync GraphqlApi, a merged API has different attributes. The `schema` attribute is mandatory for GraphQL APIs. It doesn't exist for merged APIs. So it's necessary to create a new construct to support Merged APIs.

I have also created a feature request for initial discussions on this topic: https://github.com/aws/aws-cdk/issues/25960

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @jumic
| Author(s)           | @jumic
| API Bar Raiser      | 
| Stakeholders        | 

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by rix0rrr** [comment]
We talked during the Office Hours, and we agreed that this change should be small enough that it doesn't need a full RFC.

We will deprecate the `schema: ISchema` in favor of a new field that will be typed as an enum-like class, to decide between a schema-based API or a merged API.

**Comment by jumic** [comment]
I implemented a solution without new L2 construct: https://github.com/aws/aws-cdk/pull/26895
So let's close this RFC issue.
@rix0rrr Thanks for our help!

**Comment by mrgrain** [comment]
We went down a different route than this RFC had proposed.
