### ISSUE TITLE
Thanks for this context. If more options are likely to added, I'd prefer to see this as an enum like class instead of an actual enum so that it's more extensible if options or props need to be added to potential auth types.

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk-rfcs#527]
.....I'd prefer to see this as an enum like class instead of an actual enum so that it's more extensible if options or props need to be added to potential auth types.

_Originally posted by @TheRealAmazonKendra in https://github.com/aws/aws-cdk-rfcs/pull/506#discussion_r1254020732_
            
Have replaced using the AuthType ENUM in favor of a Authorizer Class, which today, only returns the type of authorizer  ( iam or none ), but will provide a non breaking path for any future auth models that may appear.

**Comment by mrgrain** [comment]
This seems to be created as a separate issue by mistake.
