### ISSUE TITLE
RFC Pipeline does not run Linting automatically.. 

### ISSUE THREAD

**Issue by mrpackethead** [aws/aws-cdk-rfcs#530]
Could the pipeline that handles a PR to this repo, be configured to run the Linting automatically, rather than have to have someone with the appropriate permissions to kick it off?

This would save time for both reveiwers and submitters.

It woudl also be very helpful if the linting specification was highlighted somwhere, ( perhaps in one of the guides ), as the 'standards' for linting markdown are wide and varied.

**Comment by mrgrain** [comment]
Linter now runs automatically and is called out in the [docs](https://github.com/aws/aws-cdk-rfcs#4-rfc-document).
While technically possible, auto-fixing PRs is not trivial and not something we are going to look into at the moment.

The requirements are laid out in this file: https://github.com/aws/aws-cdk-rfcs/blob/main/.markdownlint.json
If you have any specific suggestions on how to highlight them further (short of writing them out as prose), please let us know.
