### ISSUE TITLE
Docker-less dependency resolution (CDK \ SAM)

### ISSUE THREAD

**Issue by CoreOxide** [aws/aws-cdk-rfcs#579]
## Description

Today, CDK deploy uses docker as it's backend to collect and install dependencies. I'm proposing a way to to that without using Docker. It will also allow building for different OS targets and Lambda runtimes.

There are 2 ways to build without docker:

1. Using native dependency resolution using PIP flags.
2. Using AWS CloudShell (most useful for building Lambda Layers).

As far as I understand, it can be incorporated into [PythonFunction](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk.aws_lambda_python_alpha/PythonFunction.html) or SAM (which also uses Docker under the hood).

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @CoreOxide
| Author(s)           | @alias, @alias, @alias
| API Bar Raiser      | @alias
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `status/api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by evgenyka** [comment]
Thank you for submitting your RFC! Please be aware that the RFC process is currently on hold, as we announced in August 2023, and we won't be able to review it immediately. We will resume the review of this request once we have clarified the future of the RFC process. I suggest keeping the RFC in status/proposed in the meantime.

**Comment by CoreOxide** [comment]
Thanks @evgenyka , I will check in periodically.

**Comment by mrpackethead** [comment]
Will it auto-close for non activity?

**Comment by CoreOxide** [comment]
> Will it auto-close for non activity?

I will try to follow the RFC process renewal and this thread so it won't be lost to time.

**Comment by evgenyka** [comment]
Not a priority at the moment. Also, this is a feature request in an Experimental (alpha) module. Suggest building your own construct, if you are interested in exploring this concept, and then submit via PR.
