### ISSUE TITLE
ARN retrieval function consistency for CDK constructs

### ISSUE THREAD

**Issue by sdpoueme** [aws/aws-cdk-rfcs#581]
## Description

Customers use ARN to wire CDK applications and build custom constructs. The ideal way to retrieve ARNs is to leverage a function attached to the CDK object and extract the value. In most cases, there is no consistent way to retrieve ARNs with CDK. Each construct implements its own method and it impacts developer experience.

This consistency will make code easier to read and maintain across organizations. In addition, it will help developers adopting new resources faster. Developers can implicitly guess the function required to retrieve ARNs.

## Short description of the proposed feature.

Developers may benefit from a consistent method to retrieve ARNs regardless of the service. e.g: myresource.getARN()

That function will be available to all CDK resources and will use the specific attribute for each to return the ARN value.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | sdpoueme
| Author(s)           | sdpoueme, effearts
| API Bar Raiser      | To be defined
| Stakeholders        | bmckinle

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `status/api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by evgenyka** [comment]
No plans to implement. The implementation drawbacks are too many to warrant the cost. Suggest contributing via PR.

**Comment by sdpoueme** [comment]
Thanks for the feedback @evgenyka. We will identify the resources to limit the scope and submit PRs for each of the resources.
