### ISSUE TITLE
Add L2 construct for aws_controltower.CfnEnabledControl

### ISSUE THREAD

**Issue by igirardi** [aws/aws-cdk-rfcs#613]
## Description

Control Tower has an [enable control resource]( https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_controltower.CfnEnabledControl.html). There is [guidance](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/deploy-and-manage-aws-control-tower-controls-by-using-aws-cdk-and-aws-cloudformation.html) how to use this construct for customers (currently being used by 50+ customers). We would like to provide this functionality in `aws-cdk-lib`.

Customers would want to give a target and list of controls to enable (or a list of targets and list of controls to enable) instead of adding a different L1 construct for each target and control.

By using L2 construct this would be simpler for customers to manage the controls instead of using looping mechanisms.
Currenlty the inputs are only strings that are fully qualified arns and we would like to simplify the input, for example OU id or OU path instead of OU arn.

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @igirardi
| Author(s)           | @igirardi, @tylersouthwick
| API Bar Raiser      | 
| Stakeholders        | @tylersouthwick

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [ ] API bar raiser assigned (ping us at [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [ ] Kick off meeting
- [ ] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `status/api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

**Comment by evgenyka** [comment]
@igirardi As we [communicated](https://cdk-dev.slack.com/archives/C018XT6REKT/p1702066379974819 ) via cdk.dev slack channel, for community contributors who looking to share L2 constructs for services and methods not yet available in the AWS Construct Library, we request that these be published to the [Construct Hub](https://constructs.dev/). If you need assistance getting started, we recommend reaching out to [cdk.dev](http://cdk.dev/) slack channel.
