### ISSUE TITLE
CDK Code Generation from AWS Console

### ISSUE THREAD

**Issue by PaulMaddox** [aws/aws-cdk-rfcs#65]
We should integrate the AWS CDK into the console / getting started experience for every AWS service.

#thinkbig

### Use Case

As an AWS user, I want to be able to explore and play around with a new service via the AWS Management Console, but then quickly transition to infrastructure as/in code. 

### Proposed Solution

- Customer browses to a service console in their browser and creates a resource via a getting started wizard

- On the final screen there are a couple of new buttons: `Create with AWS CDK`, and `Create with AWS CDK (pipeline)`.

- `Create with AWS CDK` will automatically generate a CDK project, and offer it as a ZIP that can be downloaded. The project will contain a single construct that is being deployed, with the configuration parameters the customer set during the wizard. The UI will show a helpful `Getting started with the CDK` tutorial to walk them through deploying it. 

- `Create with AWS CDK (pipeline)` will do the same as above, but automatically check the CDK project into a CodeCommit or GitHub repository, and setup AWS CodePipeline to automatically test and deploy the project.

This assumes that we have constructs/patterns that match our first experience management console wizards.

This functionality should be bundled up, and provided as a self-service library for AWS service owners to easily integrate into their consoles to maximize adoption.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by luchees** [comment]
Some time ago I found this repo which does something similar: https://github.com/iann0036/AWSConsoleRecorder
Might be interesting to see how they coped with it.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to [aws/aws-cdk](https://github.com/aws/aws-cdk/) directly or self-publishing to Construct Hub.
