### ISSUE TITLE
StackSets Support

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#66]
## Description

Allow users to define a template through AWS CDK constructs and deploy as a Self-Managed CloudFormation StackSet.

* User defines stack set the same way as normal cdk stack
* When user executes `cdk deploy` it would create a stack set if it does not exist or update an existing stack set + existing stack set instances.

Proposed Scope:
* Create New **Self-Managed** Stack Set ([docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStackSet.html )).
* Update Existing **Self-Managed** Stack Set:
  * Update includes updating existing Stack Set instances as well
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackSet.html
  * https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackInstances.html
* Ability to set stack set configuration/deployment properties:
  * Administration Role, Execution Role, Fault Tolerance, Concurrency, etc. 

Out of Scope for v1 (May be iteratively added in future):
* Service-Managed Stack Set
* Add/Remove stack set instances by ID or OU

## Roles

| Role                | User
|---------------------|------------------------------
| Proposed by         | @linsona
| Author(s)           | @linsona
| API Bar Raiser      | @skinny85
| Stakeholders        | @alias, @alias, @alias

> See [RFC Process](https://github.com/aws/aws-cdk-rfcs#rfc-process) for details

## Workflow

- [x] Tracking issue created (label: `status/proposed`)
- [x] API bar raiser assigned (ping us at
  [#aws-cdk-rfcs](https://cdk-dev.slack.com/archives/C025ZFGMUCD) if needed)
- [x] Kick off meeting
- [x] RFC pull request submitted (label: `status/review`)
- [ ] Community reach out (via Slack and/or Twitter)
- [ ] API signed-off (label `api-approved` applied to pull request)
- [ ] Final comments period (label: `status/final-comments-period`)
- [ ] Approved and merged (label: `status/approved`)
- [ ] Execution plan submitted (label: `status/planning`)
- [ ] Plan approved and merged (label: `status/implementing`)
- [ ] Implementation complete (label: `status/done`)

---

> Author is responsible to progress the RFC according to this checklist, and
apply the relevant labels to this issue so that the RFC table in README gets
updated.

Related: https://github.com/aws/aws-cdk/issues/11896

**Comment by timpur** [comment]
Any update on this ?

**Comment by AntonioAngelino** [comment]
Any news?

**Comment by apidinom** [comment]
Any update on this ?

**Comment by JamieMcKernanKaizen** [comment]
It would be good to see some progress on this

**Comment by AntonioAngelino** [comment]
@eladb Do you have any update? 🙏 

We would love to use AWS CDK in combination with AWS Org. and CloudFormation StackSets.

**Comment by corrjo** [comment]
Do we know what actually needs to be done to implement this? Would love to be able to deploy multiple instances from a single place. Happy to help however I can to make this happen.

**Comment by eroteme** [comment]
I would also love to be able to deploy stacksets via CDK. 
We have lots of accounts under a centrally managed organisation account. Recently our team was required to create all sorts of AWS resources in these accounts for initialisation purposes. The aws resources required would be defined via Cloudformation from other teams and applying them in the main org account using stacksets was a good way to achieve this. 
We basically create the stackset in the org account (service managed) and  apply stackset instances to an org tree based on OU; any accounts under that OU will get the resources required.

The issue we had is that some teams wanted to use CDK to create their Cloudformation but stacksets are not currently supported. The way we got around this was to make the a cloudformation template via `cdk synth` and apply that template using simple bash script using aws-cli. It wasn't a pretty solution but worked. We didn't want to put too much dev time into making lambda functions/custom resource definitions etc if this ticket was close to being complete. Do we know how long until stacksets are supported under CDK?

From what issues I saw, CDK needs to be able to do the following:

1. As we used service managed permissions we need to allow the org account access to all sub accounts ( as per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-enable-trusted-access.html). 
2. Allow CDK to create a stackset into a single account (org account) using a cloudformation template (from 1 or more CDK apps)
3. Have a way for CDK to apply stacksets instances to (either accountId or Org OU) and region

Maybe there is a better way, I'm open to suggestions :)

**Comment by ookangzheng** [comment]
We also have 2 OU and each has its own sandbox. I hope cdk can support stacksets too~~ 
https://aws.amazon.com/blogs/aws/new-use-aws-cloudformation-stacksets-for-multiple-accounts-in-an-aws-organization/

**Comment by dejonghe** [comment]
Also critical for my team, anyone using Control Tower for large orgs needs this.

**Comment by eladb** [comment]
> Also critical for my team, anyone using Control Tower for large orgs needs this. 

@dejonghe can you please describe your use case in more detail? In what way do you wish to use stack sets?

You can technically define a CDK stack, synth a template and deploy it through StackSets. What additional support would you expect from the CDK for this scenario?

**Comment by dejonghe** [comment]
I guess that routes seems like it would fit. 
I would say it would be nice to be able to use the same deploy mechanism for stack sets. We're moving off of a custom cloudformation deployment tool that prepped out CFN, stashed it in S3 in a versioned prefix, as well as many other things but we had support for stacksets. 
Use case is that we are using Control tower and have things that need to be deployed to every account, and should be controlled / owned by the master account. 
What I'd like to see is a core.StackSet that takes a list of accounts or an OU or something. I know that this isn't a simple change based on the way things are built up in CDK. 
Using the same deployment mechanism is really what I would want.

**Comment by IngussNeilands** [comment]
👀

**Comment by dsudduth** [comment]
@eladb I would have to agree with @dejonghe.

Between CloudFormation, AWS CDK, and AWS SAM, the ProServe team definitely get a ton of questions from our customers surrounding the variations in tooling and lack of (full) integration. Control Tower and StackSets are the best option we have for easily deploying and maintaining services that need to exist within every account; a common pattern for the enterprise where operational resources are centrally managed.

CDK has the potential to be the go-to tool. I know I'm a fan. But, we definitely need to solve for "deployment at scale" whether that means integrating with StackSets or a separate mechanism. Either way, it would be great if we can avoid context switching (different tools) to get the job done.

**Comment by paul-ge** [comment]
Could below help?: -

https://docs.aws.amazon.com/cdk/latest/guide/stack_how_to_create_multiple_stacks.html

**Comment by dsudduth** [comment]
> Could below help?: -
> 
> 
> 
> https://docs.aws.amazon.com/cdk/latest/guide/stack_how_to_create_multiple_stacks.html
> 
> 
> 
> 

Hi @paul-ge ,

I'm afraid not. These are fundamentally different ideas. The doc you shared provides an example of multiple CDK stacks which makes it easy to modularize code, but still deploys to a single account. What we're discussing is deployment across all accounts by leveraging managed StackSets in CloudFormation.

**Comment by pgarbe** [comment]
Is anyone working on that? I'd like to have a StackSet constructs which accepts a Stack property as input. But I'm running into issues during synth, as the "StackSetStack" requires the output of the other stack which will be written only at the end of the synth.

**Comment by McDoit** [comment]
I have just stumbled on this with StackSets and the CDK, but I assume one of the bigger issues would be the assets CDK provisions in S3 and lambda for Custom Resources and similar applications?
Is there any way to gather them in a stack and apply `aws:PrincipalOrgPaths` 
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html
to their access roles?

**Comment by paulwehage** [comment]
Any updates on this?

**Comment by redbaron** [comment]
It is possible to deploy CDK as a StackSets  by using intermediate`Stage`. It is not pretty, but doable:

```
const app = new cdk.App()

// Stage allows us to synth CF template for Stacks added to it
const stage = new cdk.Stage(app, "Stage")
new StackToDeployAsStackset(stage, "XYZ")
const stackSetTemplateObj = stage.synth().stacks[0].template

const stackSetDeployer = new cdk.Stack(app, "StackSetDeployer")
new cdk.CfnStackSet(stackSetDeployer, "XYZASaStackSet", {
            ...
            templateBody: JSON.stringify(stackSetTemplateObj),
})
```

**Comment by IngussNeilands** [comment]
> It is possible to deploy CDK as a StackSets by using intermediate`Stage`. It is not pretty, but doable:
> 
> ```
> const app = new cdk.App()
> 
> // Stage allows us to synth CF template for Stacks added to it
> const stage = new cdk.Stage(app, "Stage")
> new StackToDeployAsStackset(stage, "XYZ")
> const stackSetTemplateObj = stage.synth().stacks[0].template
> 
> const stackSetDeployer = new cdk.Stack(app, "StackSetDeployer")
> new cdk.CfnStackSet(stackSetDeployer, "XYZASaStackSet", {
>             ...
>             templateBody: JSON.stringify(stackSetTemplateObj),
> })
> ```

Use of this method may trigger the following error `Unable to fetch parameters [/cdk-bootstrap/hnb659fds/version] from parameter store for this account.`

It will happen when creating stackset for the account that is not bootstrapped.

I fixed this errror by removing the following sections from template before json dump:

- ["Resources"]["CDKMetadata"]
- ["Rules"]["CheckBootstrapVersion"]
- ["Parameters"]["BootstrapVersion"]

**Comment by pgarbe** [comment]
If you don't want to have the bootstrap check, you can use the `BootstraplessSynthesizer`. 

Must work like this:
```
new StackToDeployAsStackset(stage, "XYZ", { synthesizer: new cdk.BootstraplessSynthesizer({}) });
```

**Comment by 0xjjoyy** [comment]
@redbaron Nice snippet! Were you able to also figure out a way to take in and pass parameters to the stackset? CfnParameter must be part of a stack, so I'm not sure how to pass parameters here.

**Comment by tvb** [comment]
> It is possible to deploy CDK as a StackSets by using intermediate`Stage`. It is not pretty, but doable:
> 
> ```
> const app = new cdk.App()
> 
> // Stage allows us to synth CF template for Stacks added to it
> const stage = new cdk.Stage(app, "Stage")
> new StackToDeployAsStackset(stage, "XYZ")
> const stackSetTemplateObj = stage.synth().stacks[0].template
> 
> const stackSetDeployer = new cdk.Stack(app, "StackSetDeployer")
> new cdk.CfnStackSet(stackSetDeployer, "XYZASaStackSet", {
>             ...
>             templateBody: JSON.stringify(stackSetTemplateObj),
> })
> ```

Are there any plans on natively integrate this with the CDK to make StackSets possible out-of-the-box?

**Comment by eladb** [comment]
We currently don't have concrete plans to add support for StackSets, but your comments and +1s will help us prioritize.

**Comment by tvb** [comment]
Hi @eladb I think it would be a great addition considering AWS's push for multi account organizations

**Comment by jacobsnapp** [comment]
As a customer working closely with an AWS ProServ team, I am very interested in more support for StackSets with CDK. We currently manage many StackSets across multiple AWS Control Tower environments using custom tooling wrapped around CDK.

I recently used the pattern suggested by @redbaron leveraging CfnStackSet and it got me very excited! I would love to see more CDK support for StackSets, including the ability to import existing StackSets into CfnStackSet or the L2 equivalent.

**Comment by RaeesBhatti** [comment]
> It is possible to deploy CDK as a StackSets by using intermediate`Stage`. It is not pretty, but doable:
> 
> ```
> const app = new cdk.App()
> 
> // Stage allows us to synth CF template for Stacks added to it
> const stage = new cdk.Stage(app, "Stage")
> new StackToDeployAsStackset(stage, "XYZ")
> const stackSetTemplateObj = stage.synth().stacks[0].template
> 
> const stackSetDeployer = new cdk.Stack(app, "StackSetDeployer")
> new cdk.CfnStackSet(stackSetDeployer, "XYZASaStackSet", {
>             ...
>             templateBody: JSON.stringify(stackSetTemplateObj),
> })
> ```

This works for resources that don't require assets but not for resources like Lambda which require Asset Parameters to work. Is it possible to deploy the assets along with the `StackSetDeployer`?

**Comment by michft-v** [comment]
Same as above. I work deploying CDK (Java version) as an enterprise stack. Having issues with conflicts from StackSet created resources and CDK created resources. Things like AWS Config recorders information, VPC ARN and Stackset deployed IAM roles end up being manually entered into CDK which is not really the point of programatically deploying your stacks.

Interested in being kept up to date with any progress.

**Comment by tvb** [comment]
> It is possible to deploy CDK as a StackSets by using intermediate`Stage`. It is not pretty, but doable:
> 
> ```
> const app = new cdk.App()
> 
> // Stage allows us to synth CF template for Stacks added to it
> const stage = new cdk.Stage(app, "Stage")
> new StackToDeployAsStackset(stage, "XYZ")
> const stackSetTemplateObj = stage.synth().stacks[0].template
> 
> const stackSetDeployer = new cdk.Stack(app, "StackSetDeployer")
> new cdk.CfnStackSet(stackSetDeployer, "XYZASaStackSet", {
>             ...
>             templateBody: JSON.stringify(stackSetTemplateObj),
> })
> ```

This approach seems to be broken since version 1.102.0. It now tries to deploy the staged stack also resulting in unwanted extra resources being deployed.

**Comment by McDoit** [comment]
> This approach seems to be broken since version 1.102.0. It now tries to deploy the staged stack also resulting in unwanted extra resources being deployed.

Seems to be related to #14379
Testing around with the patterns there and it seems like `--all` instead of `*` works as a workaround!

Was this the intended behavior @otaviomacedo ?

**Comment by tvb** [comment]
> Testing around with the patterns there and it seems like `--all` instead of `*` works as a workaround!

Yes, I noticed. Thank you.

**Comment by robertjan-b** [comment]
@RaeesBhatti it is possible to publish the assets in the account where you deploy the stacksets using cdk-assets:
`cdk-assets publish --path cdk.out/assembly-Stage/StackSetDeployer.assets.json --verbose`

You will have to make sure that the rest of the accounts can access the assets in the S3 bucket by updating the bootstrapping template.

**Comment by RaeesBhatti** [comment]
Thanks for the suggestion @robertjan-b . I'll try that

**Comment by robertjan-b** [comment]
The way to create the stackset stack looks a lot cleaner using the following method: https://github.com/aws/aws-cdk/issues/11896

**Comment by brunobodson** [comment]
> Thanks for the suggestion @robertjan-b . I'll try that

@RaeesBhatti, did you manage to make it work with the assets? Looking forward to your findings!

**Comment by tvb** [comment]
It seems StackSets is kinda broken in CDKv2. It tries to resolve the `cdk-bootstrap` parameter from the Parameter Store in my taget accounts too..

```
Unable to fetch parameters [/cdk-bootstrap/xxxxx/version] from parameter store for this account.
```

**Comment by skinny85** [comment]
@tvb do you mind opening us an issue in the main CDK repository (https://github.com/aws/aws-cdk/issues/new/choose), showing your code, and the exact command you execute, and the full error that you get?

**Comment by bsweeney-gingerio** [comment]
Using StackSets to deploy CDK stacks across accounts/OUs in an organization would be helpful for customers who need to ensure certain resources are present in every account to meet compliance requirements. For large organizations, it also obviates the need to automate CDK bootstrapping every account as part of a CDK Pipelines deployment. For additional security, I believe CDK should refuse (at least warn) to bootstrap StackSets in the Organizations management account, instead requiring that the bootstrap environment exist in a StackSets delegated administrator.

In the meantime, one way my team gets StackSet support from CDK (in addition to previous suggestions) is to write the synthesized template to the CDK assets S3 bucket:

```typescript
const stackTemplateAsset = new assets.Asset(
  this,
  `${stackClass.name}TemplateAsset`,
  {
    path: stackTemplatePath,
  }
);
```

`stackTemplatePath` is the filesystem path to the synthesized template written to a temporary directory, since I didn't see a way to make this work directly with the JSON. The template can then be passed to the new `CfnStackSet` as `templateUrl: stackTemplateAsset.httpUrl`.

**Comment by jabalsad** [comment]
Is this RFC still moving forward?

**Comment by pgarbe** [comment]
There seems to be some movement for ServiceCatalog Products. They support now [assets](https://github.com/aws/aws-cdk/pull/22857). 

I'm working on a similar solution for StackSets here: https://github.com/pgarbe/cdk-stackset

**Comment by PrettySolution** [comment]
Do you really need StackSets if you have waves? what is the use case?
`
    const subAccountLevelWave = pipeline.addWave('subAccountLevelWave')
    subAccountLevelENVs.forEach(env => {
      subAccountLevelWave.addStage(new AccountLevelStage(this, `level-${env.region}-in-${env.account}`, {
        env, repo, logAggregatorBucketName
      }))
    })
`

**Comment by bsweeney-gingerio** [comment]
Use case: ensure that any account added to an organization has a CDK bootstrap template applied so that it can be included in a pipeline wave. Manage that template using CDK.

**Comment by gbvanrenswoude** [comment]
As long as you do not use Assets in your ProductStack this works pretty neat:

```
export const createStackSet = (
  scope: Construct,
  name: string,
  stack: sc.ProductStack,
) => {
  return new CfnStackSet(scope, name, {
    permissionModel: 'SERVICE_MANAGED',
    autoDeployment: {
      enabled: true,
      retainStacksOnAccountRemoval: false,
    },
    capabilities: [
      'CAPABILITY_IAM',
      'CAPABILITY_NAMED_IAM',
      'CAPABILITY_AUTO_EXPAND',
    ],
    description: `StackSet for ${name}`,
    operationPreferences: {
      failureToleranceCount: 25,
      maxConcurrentCount: 25,
    },
    parameters: [],
    stackSetName: name,
    templateUrl:
      sc.CloudFormationTemplate.fromProductStack(stack).bind(scope).httpUrl,
    stackInstancesGroup: [
      {
        deploymentTargets: {
          organizationalUnitIds: [
            scope.node.tryGetContext(ContextProps.OU_ROOT_ID),
          ],
        },
        regions: ['eu-west-1'],
      },
    ],
  });
};
```

**Comment by ericzbeard** [comment]
See https://github.com/cdklabs/cdk-stacksets/

**Comment by RichiCoder1** [comment]
> See [cdklabs/cdk-stacksets](https://github.com/cdklabs/cdk-stacksets/)

Ayy, awesome to see something semi official! I wonder if the asset work from @pgarbe's repo (https://github.com/pgarbe/cdk-stackset) couldn't be carried over to partially address https://github.com/cdklabs/cdk-stacksets/issues/58

**Comment by stekern** [comment]
Are there any plans to move the construct from https://github.com/cdklabs/cdk-stacksets/ to the main AWS CDK repository at https://github.com/aws/aws-cdk?

It's not entirely clear to me what the different governance model and lifecycle is for code in these two different GitHub organizations. To me it seems like `cdklabs` hosts code that is less official, more experimental and potentially has less support and development, so I tend to be vary of using it in production.

Could you provide any insights on this?
