### ISSUE TITLE
Monitoring Packs

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#67]
|PR|Champion|
|--|--------|
|# |        |

## Description

A centralized dashboard and alarming settings are standard operational patterns for cloud services. We currently have the capabilities to define a CloudWatch Dashboard and setup alarms but it would be valuable to be able to define a centralized monitoring "hub" which constructs can automatically discover and "register" to.

Ideally, whenever a construct is added to a stack (at any level), it can also add dashboard widgets and define a default set of alarms that will trigger a common monitoring alerting system.

It would be valuable to define a pattern for exposing "monitoring packs" for constructs. The idea is that constructs can bundle a set of monitoring settings such as alarms and dashboard graphs/widgets which can automatically "register" into a stack/app-central monitoring system.
- All L2s include dashboard/monitoring packs (like watchful)
- Normalize metrics across L2s (we don't have a linter rule for metrics)

## Progress

- [x] Tracking Issue Created
- [ ] RFC PR Created 
- [ ] Core Team Member Assigned 
- [ ] Initial Approval / Final Comment Period
- [ ] Ready For Implementation
    
    - [ ] implementation issue 1
- [ ] Resolved

**Comment by pgarbe** [comment]
Just came over the same topic as I want to offer some alarms as part of my Construct that is shared as library. Unfortunately, there's no standard yet like `metricsXXX()` or `grantXXX()`.

I was thinking about something similar to this: 

```
class MyConstruct { 
  sendAlarmsTo(topic: sns.ITopic, options: MyAlarmOptions) {
    // Create CW alarms... 
  }
}
```

An additional interface could help to identify such Constructs.

**Comment by mrgrain** [comment]
Marking this RFCs as `stale` since there has been little recent activity and it is not currently close to getting accepted as-is. We appreciate the effort that has gone into this proposal. Marking an RFCs as stale is not a one-way door. If you have made substantial changes to the proposal, please open a new issue/RFC. You might also consider raising a PR to https://github.com/aws/aws-cdk/ directly or self-publishing to Construct Hub.
