### ISSUE TITLE
AWS Account Alias Resource

### ISSUE THREAD

**Issue by hoegertn** [aws/aws-cdk-rfcs#86]
Create an L2 for AWS account aliases using a custom resource

### Proposed Solution

Custom resource setting the account alias. CFN support is not available

* [X] :wave: I will implement this feature request

---

This is a :rocket: Feature Request

**Comment by eladb** [comment]
This is a very interesting idea. I am transferring this to the RFC repo. Please follow the [RFC Repo README](https://github.com/aws/aws-cdk-rfcs/README.md) in order to submit this as an RFC.

**Comment by pgollucci** [comment]
Interested

**Comment by pgollucci** [comment]
https://github.com/p6m7g8/p6-namer/ is this.  It needs to move from a CustomResource to an AwsCustomResource since its just an API call.  Happy to pull this out and put it in as a PR for @aws-cdk/aws-iam

**Comment by awsmjs** [comment]
Closing this ticket. We believe the functionality is beneficial, but does not intersect with the core framework and should be vended and maintained separately.
