### ISSUE TITLE
cdk assert: Regression test support

### ISSUE THREAD

**Issue by eladb** [aws/aws-cdk-rfcs#89]
Support an ability to "regress" a synthesized template against a checked-in version. Think of it as a template "lock file". 

This capability allows developers to make sure that infrastructure changes are audited (code reviewed) and committed to the code repository. It also allows developers to discover unexpected infra changes before pushing them to a CI/CD pipeline (as they are represented as file diffs).

Here's a proposed usage:

```
$ cdk assert --lockfile ./mystack.json [stack]
```

This will synthesize the specified stack and will diff it with the contents of `./mystack.json`. 

1. If the file doesn't exist, it will indicate that this is a new file and exit with non-zero exit code.
2. If the file exists, and equals, it will just exit with 0
3. If the file exists, and differs, it will print a friendly diff, update the file, and exit with a non-zero exit code.

This command is designed to be executed as a package test. In case the user pushes a change to the code that resulted in a template change, but did not run the test (which means they did not "acknowledge" the change), the test will fail with informative information. If the user runs the test locally, the first time will display the diff and modify the file, which will be surfaced when the user commits their code into the repository.

Consider if we want to merge this functionality with `cdk-integ` (#113, aws/aws-cdk#40, aws/aws-cdk#41).

**Comment by eladb** [comment]
Duplicate with #31

**Comment by inakianduaga** [comment]
Would be nice to have YAML conversion for the snapshots out of the box. We are currently using a custom Jest extension that is doing the equivalent of  

```ts
import { SynthUtils } from '@aws-cdk/assert'
import * as jsYaml from 'js-yaml'

expect(
        jsYaml.dump(SynthUtils.synthesize(stack).template)
      ).toMatchSnapshot()
```

which we provide as a 

```ts
expect(stack).toMatchCdkSnapshot(selector?: (artifact: CloudFormationStackArtifact) => object)
```

where the selector can be used to pick a specific part of the template (or do any sort of transformation) that we end up snapshotting. 

This is much more readable that dumping plain JS diffs (yaml > JS in this case)
